
import { Nunito } from 'next/font/google';
import Navbar from 'app/components/navbar/Navbar.tsx';

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Navbar />
        {children}</body>
    </html>
  )
}
